name = "JSPlots"
uuid = "05744359-7ec0-46c8-9490-aaa1bc06b10a"
authors = ["Stuart Baumann <stuart@stuartbaumann.com>"]
version = "0.1.0"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DuckDB = "d2f5444f-75bc-4fdf-ac35-56f514c445e1"
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"
VegaLite = "112f6efa-9a02-5b7d-90c0-432ed331239a"

[compat]
Base64 = "^1"
CSV = "^0.10"
DBInterface = "^2"
DataFrames = "^1"
Dates = "^1"
DuckDB = "^1"
Infiltrator = "^1"
JSON = "0.21"
LinearAlgebra = "^1"
Markdown = "^1"
TimeZones = "^1"
VegaLite = "1.0.0"
julia = "^1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
