name = "JSPlots"
uuid = "05744359-7ec0-46c8-9490-aaa1bc06b10a"
authors = ["Stuart Baumann <stuart@stuartbaumann.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DuckDB = "d2f5444f-75bc-4fdf-ac35-56f514c445e1"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
