name = "JSPlots"
uuid = "05744359-7ec0-46c8-9490-aaa1bc06b10a"
authors = ["Stuart Baumann <stuart@stuartbaumann.com>"]
version = "0.4.2"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
DuckDB = "d2f5444f-75bc-4fdf-ac35-56f514c445e1"
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
RefinedSlippage = "f102acab-2a34-462b-8f40-530debd6834f"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"
VegaLite = "112f6efa-9a02-5b7d-90c0-432ed331239a"

[compat]
Base64 = "^1"
CSV = "^0.10"
CategoricalArrays = "^1"
Clustering = "^0.15"
DBInterface = "^2"
DataFrames = "^1"
DataFramesMeta = "^0.15"
Dates = "^1"
Distances = "^0.10"
DuckDB = "^1"
HighFrequencyCovariance = "0.5.2"
Infiltrator = "^1"
JSON = "^0.21"
LinearAlgebra = "^1"
Markdown = "^1"
OrderedCollections = "^1.8.1"
StableRNGs = "^1"
Statistics = "^1"
StatsBase = "^0.33, ^0.34"
TimeZones = "^1"
VegaLite = "^3"
julia = "^1.4"

[extras]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
HighFrequencyCovariance = "c79ce38c-73ba-4c3d-834c-fb94999fb590"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
docs = ["HighFrequencyCovariance"]
test = ["Test", "Plots", "CairoMakie", "Random", "Statistics"]
